"""
Validators Module.

Purpose: Safety validation for file operations and suggestions.
Implements read-only and suggest-only policy.
"""

from typing import List, Tuple, Optional
from pathlib import Path
import fnmatch


# Global safeguard rules configuration
SAFEGUARD_RULES = {
    "readonly_patterns": ["*.json", "*.yaml", "*.yml", ".env*", "*config*"],
    "max_lines_without_review": 1000,
    "skip_generated": True,
    "require_approval_for": ["__init__.py", "conftest.py", "settings.py"]
}


class FileGuardrails:
    """
    Filters and validates file operations for safety.
    
    Implements read-only and suggest-only policy:
    - Blocks write operations to sensitive files
    - Warns on large files
    - Detects generated code
    """
    
    # File patterns that are read-only
    READ_ONLY_PATTERNS: List[str] = [
        "*.json",
        "*.yaml",
        "*.yml",
        ".env*",
        "*config*",
        "*.lock",
        "*.toml",
        "Dockerfile*",
        "docker-compose*",
        ".git*",
        "*.min.js",
        "*.min.css",
    ]
    
    # File patterns that indicate generated code
    GENERATED_PATTERNS: List[str] = [
        "*generated*",
        "*auto-generated*",
        "*_pb2.py",  # Protobuf
        "*_pb2_grpc.py",
    ]
    
    # Files requiring explicit approval
    APPROVAL_REQUIRED_FILES: List[str] = [
        "__init__.py",
        "conftest.py",
        "settings.py",
        "config.py",
        "models.py",  # Database models
    ]
    
    def __init__(
        self,
        max_lines_without_review: int = 1000,
        enable_generated_detection: bool = True,
    ):
        self.max_lines = max_lines_without_review
        self.enable_generated_detection = enable_generated_detection
        
    def can_suggest_changes(self, file_path: str) -> Tuple[bool, Optional[str]]:
        """
        Check if changes can be suggested for a file.
        
        Args:
            file_path: Path to the file
            
        Returns:
            (is_allowed, reason_if_not)
        """
        path = Path(file_path)
        
        # Check read-only patterns
        for pattern in self.READ_ONLY_PATTERNS:
            if fnmatch.fnmatch(path.name, pattern):
                return False, f"File matches read-only pattern: {pattern}"
        
        # Check if file is in approval-required list
        if path.name in self.APPROVAL_REQUIRED_FILES:
            return True, "WARNING: This file requires explicit approval"
        
        # Check file size
        try:
            with open(file_path, 'r') as f:
                line_count = sum(1 for _ in f)
                if line_count > self.max_lines:
                    return True, f"WARNING: Large file ({line_count} lines), review carefully"
        except Exception:
            pass  # Can't read, assume OK
        
        # Check for generated code
        if self.enable_generated_detection and self._is_generated_code(file_path):
            return False, "File appears to be auto-generated code"
        
        return True, None
    
    def _is_generated_code(self, file_path: str) -> bool:
        """Detect if file contains auto-generated code."""
        # Check file name patterns
        for pattern in self.GENERATED_PATTERNS:
            if fnmatch.fnmatch(file_path, pattern):
                return True
        
        # Check for common generated code markers in first 10 lines
        try:
            with open(file_path, 'r') as f:
                header = ''.join(f.readline() for _ in range(10))
                markers = [
                    "# Generated by",
                    "# AUTO-GENERATED",
                    "# This file was generated",
                    "@generated",
                ]
                return any(marker in header for marker in markers)
        except Exception:
            return False
    
    def validate_suggestion_scope(
        self, num_files: int, max_files: int = 5
    ) -> Tuple[bool, Optional[str]]:
        """Validate that suggestion scope is reasonable."""
        if num_files > max_files:
            return False, f"Suggestion affects {num_files} files, max is {max_files}"
        return True, None


class ScopeValidator:
    """Validates that suggestions stay within reasonable scope."""
    
    def __init__(self, max_files: int = 5, max_complexity: int = 20):
        self.max_files = max_files
        self.max_complexity = max_complexity
    
    def validate_plan_scope(self, plan) -> "ValidationResult":
        """Check if plan is within acceptable scope."""
        issues = []
        
        # Check file count
        if hasattr(plan, 'files_to_change') and len(plan.files_to_change) > self.max_files:
            issues.append(
                f"Plan affects {len(plan.files_to_change)} files, "
                f"maximum is {self.max_files}. Consider breaking into smaller plans."
            )
        
        # Check complexity of each change
        if hasattr(plan, 'files_to_change'):
            for file_change in plan.files_to_change:
                complexity = self._estimate_complexity(file_change)
                if complexity > self.max_complexity:
                    issues.append(
                        f"Change to {file_change.path} has complexity {complexity}, "
                        f"consider simplifying"
                    )
        
        return ValidationResult(
            is_valid=len(issues) == 0,
            issues=issues,
            severity="warning" if issues else "ok"
        )
    
    def _estimate_complexity(self, file_change) -> int:
        """Estimate complexity of a file change (placeholder)."""
        # Placeholder implementation
        # In real implementation, analyze AST complexity
        return 1


class ValidationResult:
    """Result of validation."""
    
    def __init__(self, is_valid: bool, issues: List[str], severity: str):
        self.is_valid = is_valid
        self.issues = issues
        self.severity = severity
