from typing import Dict, Any, List
from src.agent.plugins.base import AgentPluginBase
from src.tools.pr_tools import analyze_pr_files


class AutoCheckCodeQualityPlugin(AgentPluginBase):
    name = "auto_check_code_quality"
    description = "Analyze added code in PR and prepare a quality report"

    def matches(self, event: Dict[str, Any]) -> bool:
        return event.get("type") == "pr" and ("bug" in (event.get("labels") or []))

    def run(self, event: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        files_data: List[Dict[str, Any]] = event.get("files_data") or []
        issues = analyze_pr_files(files_data)
        total = sum(len(v) for v in issues.values())
        if total == 0:
            return {}
        lines = ["## 🔎 Auto Code Quality Report", ""]
        for cat in ["security", "performance", "quality"]:
            if issues.get(cat):
                lines.append(f"### {cat.title()} Issues ({len(issues[cat])})")
                for i in issues[cat][:10]:
                    lines.append(f"- [{i['severity']}] {i['file']}: {i['message']}")
                lines.append("")
        lines.append("\n*Generated by AutoCheckCodeQualityPlugin*")
        comment = "\n".join(lines)
        return {"action": "comment", "comment": comment}

