#!/usr/bin/env python3
"""GitHub Actions entrypoint for issue triage automation."""

from __future__ import annotations

import asyncio
import json
import os
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, Optional

# Ensure project root is importable when run from scripts/
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.agents.github_issue_agent import GitHubIssueAgent
from src.tools.github_tools import GitHubIssue
from src.utils.logger import get_logger

logger = get_logger(__name__)


def _load_github_event() -> Dict[str, Any]:
    event_path = os.getenv("GITHUB_EVENT_PATH")
    if not event_path:
        return {}

    path = Path(event_path)
    if not path.exists():
        logger.warning("GITHUB_EVENT_PATH does not exist: %s", event_path)
        return {}

    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _issue_from_payload(payload: Dict[str, Any]) -> Optional[GitHubIssue]:
    issue = payload.get("issue")
    if not issue:
        return None

    from datetime import datetime

    labels = [label.get("name", "") for label in issue.get("labels", []) if label.get("name")]
    assignees = [user.get("login", "") for user in issue.get("assignees", []) if user.get("login")]
    milestone = None
    if issue.get("milestone"):
        milestone = issue["milestone"].get("title")

    return GitHubIssue(
        id=issue["id"],
        number=issue["number"],
        title=issue.get("title", ""),
        body=issue.get("body") or "",
        state=issue.get("state", "open"),
        created_at=datetime.strptime(issue["created_at"], "%Y-%m-%dT%H:%M:%SZ"),
        updated_at=datetime.strptime(issue["updated_at"], "%Y-%m-%dT%H:%M:%SZ"),
        user=issue.get("user", {}).get("login", "unknown"),
        labels=labels,
        assignees=assignees,
        milestone=milestone,
        comments_count=issue.get("comments", 0),
        url=issue.get("html_url", ""),
    )


def _build_comment(analysis: Dict[str, Any]) -> str:
    labels = analysis.get("suggested_labels") or []
    labels_text = ", ".join(f"`{label}`" for label in labels) if labels else "(none)"
    confidence_pct = round(float(analysis.get("confidence", 0)) * 100, 1)

    return (
        "## 🤖 Automated issue triage\n\n"
        f"- **Category:** {analysis.get('category', 'Unknown')}\n"
        f"- **Priority:** {analysis.get('priority', 'Medium')}\n"
        f"- **Complexity:** {analysis.get('complexity', 'Medium')}\n"
        f"- **Estimated Time:** {analysis.get('estimated_time', 'TBD')}\n"
        f"- **Suggested Labels:** {labels_text}\n"
        f"- **Confidence:** {confidence_pct}%\n\n"
        "### Summary\n"
        f"{analysis.get('analysis_summary', 'No summary generated.')}\n\n"
        "_Generated by `scripts/run_ai_agent.py`._"
    )


async def _run_for_issue_event(repo: str, token: str, payload: Dict[str, Any]) -> int:
    issue = _issue_from_payload(payload)
    if issue is None:
        logger.info("No issue payload found; nothing to process")
        return 0

    owner, repo_name = repo.split("/", maxsplit=1)

    agent = GitHubIssueAgent(repo=repo, token=token, config={"test_mode": False})
    analysis = await agent.analyze_issue(issue)
    analysis_dict = asdict(analysis)

    suggested_labels = analysis_dict.get("suggested_labels") or []
    if suggested_labels:
        unique_labels = sorted(set(suggested_labels))
        agent.github_tools.add_label_to_issue(owner, repo_name, issue.number, unique_labels)

    comment_body = _build_comment(analysis_dict)
    agent.github_tools.create_issue_comment(owner, repo_name, issue.number, comment_body)

    logger.info(
        "Issue #%s triaged successfully (category=%s, priority=%s)",
        issue.number,
        analysis_dict.get("category"),
        analysis_dict.get("priority"),
    )
    return 0


async def _async_main() -> int:
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("REPO_FULL_NAME") or os.getenv("GITHUB_REPOSITORY")

    if not token:
        logger.error("GITHUB_TOKEN is required")
        return 1
    if not repo or "/" not in repo:
        logger.error("REPO_FULL_NAME or GITHUB_REPOSITORY must be set as owner/repo")
        return 1

    event_name = os.getenv("GITHUB_EVENT_NAME", "")
    payload = _load_github_event()

    if event_name == "issues":
        return await _run_for_issue_event(repo, token, payload)

    logger.info("No-op for event '%s'", event_name or "unknown")
    return 0


def main() -> int:
    try:
        return asyncio.run(_async_main())
    except Exception as exc:  # fail fast for action visibility
        logger.exception("AI agent runner failed: %s", exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
